export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGUT_USER";

export const STORE_USER_INFO = "STORE_USER_INFO";
export const STORE_SEARCHED_USER_INFO = "STORE_SEARCHED_USER_INFO";

export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIE_DETAILS = "SET_MOVIE_DETAILS";
export const SET_MOVIE_SEARCH = "SET_MOVIE_SEARCH";
export const SET_FILTERS = "SET_FILTERS";
export const SET_FILTERED_MOVIES = "SET_FILTERED_MOVIES";
export const ADD_FILTERED_MOVIES = "ADD_FILTERED_MOVIES";

export const SET_OPEN_SEARCH = "SET_OPEN_SEARCH";

export const SET_LOADING = "SET_LOADING";
export const SET_DONE = "SET_DONE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";
